export type { IEntity, ITimestamped } from './common.interfaces';
export type { IStorageStat, IRegistryHealth, IDashboardStats, IActivityFeedItem } from './dashboard.interfaces';
export type { IDockerRepository, IDockerTag, IDockerPlatform, IVulnerabilitySummary, IVulnerability, IDockerImageLayer, IDockerImageDetail } from './docker.interfaces';
export type { INuGetPackage, INuGetPackageVersion, INuGetDependencyGroup, INuGetDependency } from './nuget.interfaces';
export type { INpmPackage, INpmPackageVersion } from './npm.interfaces';
export type { IUser, ITeam, ITeamMember, IRoleDefinition, IPermissionGrant, ICreateUserRequest, IUpdateUserRequest, IChangePasswordRequest } from './rbac.interfaces';
export type { IAuditLogEntry } from './audit-log.interfaces';
export type { IAnalyticsDataPoint, IRegistryAnalytics, ITopPackage, IAnalyticsSummary } from './analytics.interfaces';
export type { IRegistryConnection, ICreateRegistryConnectionRequest, IUpdateRegistryConnectionRequest, IStorageConfig, IRetentionPolicy, ICreateRetentionPolicyRequest, IUpdateRetentionPolicyRequest, IWebhook, ICreateWebhookRequest, IUpdateWebhookRequest, IGeneralSettings, IRegistrySyncResult } from './settings.interfaces';
export type { IAuthUser, ILoginRequest, ILoginResponse, IRegistryCredential, ICreateCredentialRequest, IUpdateCredentialRequest } from './auth.interfaces';
export type { IBulkDeleteRequest, IBulkDeleteItem, IBulkDeleteResult, IBulkDeleteFailure, ICleanupVersionsRequest, IRetentionRunResult, IRegistryRepairRequest, IRegistryRepairResult, IRegistryRepairRepository, IRegistryRepairFailure } from './bulk-operations.interfaces';
export type { AgentFeature, AgentStatus, IRegistryAgentSummary, IAgentTestRequest, IAgentInfo, IAgentProcess, IAgentDisk, IAgentMaintenance, IAgentHealth, IAgentStorage, IAgentRepositoryStorage, AgentJobState, IStartGcRequest, IAgentGcJob, IRemoveRepositoryRequest, IAgentUploads, IPurgeUploadsRequest, IPurgeUploadsResult, IUpdateMaintenanceRequest, AgentLogSource, IAgentLogs, RegistryUserRole, IRegistryUser, ICreateRegistryUserRequest, IUpdateRegistryUserRequest, IRegistryUserResult, IAgentSettings, IAgentOverviewItem, ScanState, IScanRequest, IScanResult, IScanFinding, IDockerPullStats } from './agent.interfaces';
