export enum AuditAction {
  ImagePush = 0,
  ImagePull = 1,
  ImageDelete = 2,
  TagDelete = 3,
  PackagePublish = 4,
  PackageDelete = 5,
  PackageDownload = 6,
  UserCreate = 7,
  UserUpdate = 8,
  UserDelete = 9,
  TeamCreate = 10,
  TeamUpdate = 11,
  TeamDelete = 12,
  RoleAssign = 13,
  SettingsUpdate = 14,
  WebhookCreate = 15,
  WebhookDelete = 16,
  LoginSuccess = 17,
  LoginFailure = 18,
}
