export const ROUTE_PATHS = {
  DASHBOARD: '/',
  DOCKER_REPOSITORIES: '/docker',
  DOCKER_REPOSITORY_DETAIL: '/docker/:repositoryId',
  DOCKER_TAG_DETAIL: '/docker/:repositoryId/tags/:tagName',
  NUGET_PACKAGES: '/nuget',
  NUGET_PACKAGE_DETAIL: '/nuget/:packageId',
  NUGET_VERSION_DETAIL: '/nuget/:packageId/versions/:version',
  NPM_PACKAGES: '/npm',
  NPM_PACKAGE_DETAIL: '/npm/:packageName',
  NPM_VERSION_DETAIL: '/npm/:packageName/versions/:version',
  USERS: '/access/users',
  USER_DETAIL: '/access/users/:userId',
  TEAMS: '/access/teams',
  TEAM_DETAIL: '/access/teams/:teamId',
  ROLES: '/access/roles',
  AUDIT_LOGS: '/audit-logs',
  ANALYTICS: '/analytics',
  SETTINGS: '/settings',
  SETTINGS_GENERAL: '/settings/general',
  SETTINGS_REGISTRIES: '/settings/registries',
  SETTINGS_STORAGE: '/settings/storage',
  SETTINGS_RETENTION: '/settings/retention',
  SETTINGS_WEBHOOKS: '/settings/webhooks',
} as const;
